Vagrant.configure("2") do |config|
    config.vm.box = "hashicorp/precise32"
    config.vm.provision :shell, :path => "misc/bootstrap.sh"
    config.vm.network :forwarded_port, host: 8080, guest: 80
    config.vm.network :forwarded_port, host: 3306, guest: 3306
    config.vm.network :forwarded_port, host: 6379, guest: 6379
    config.vm.network "private_network", ip: "192.168.0.2"
end